let InstanceType = ./Type.dhall

in  { all =
      [ InstanceType.c5-large
      , InstanceType.c5-xlarge
      , InstanceType.c5-2xlarge
      , InstanceType.c5-4xlarge
      , InstanceType.c5a-large
      , InstanceType.c5a-xlarge
      , InstanceType.c5a-2xlarge
      , InstanceType.c5a-4xlarge
      , InstanceType.c5d-large
      , InstanceType.c5d-xlarge
      , InstanceType.c5d-2xlarge
      , InstanceType.c5d-4xlarge
      , InstanceType.c5n-large
      , InstanceType.c5n-xlarge
      , InstanceType.c5n-2xlarge
      , InstanceType.c5n-4xlarge
      , InstanceType.c6g-medium
      , InstanceType.c6g-large
      , InstanceType.c6g-xlarge
      , InstanceType.c6g-2xlarge
      , InstanceType.c6g-4xlarge
      , InstanceType.c6gd-medium
      , InstanceType.c6gd-large
      , InstanceType.c6gd-xlarge
      , InstanceType.c6gd-2xlarge
      , InstanceType.c6gd-4xlarge
      , InstanceType.c6gn-medium
      , InstanceType.c6gn-large
      , InstanceType.c6gn-xlarge
      , InstanceType.c6gn-2xlarge
      , InstanceType.c6gn-4xlarge
      , InstanceType.m4-large
      , InstanceType.m4-xlarge
      , InstanceType.m4-2xlarge
      , InstanceType.m4-4xlarge
      , InstanceType.m5-large
      , InstanceType.m5-xlarge
      , InstanceType.m5-2xlarge
      , InstanceType.m5-4xlarge
      , InstanceType.m5a-large
      , InstanceType.m5a-xlarge
      , InstanceType.m5a-2xlarge
      , InstanceType.m5a-4xlarge
      , InstanceType.m5ad-large
      , InstanceType.m5ad-xlarge
      , InstanceType.m5ad-2xlarge
      , InstanceType.m5ad-4xlarge
      , InstanceType.m5d-large
      , InstanceType.m5d-xlarge
      , InstanceType.m5d-2xlarge
      , InstanceType.m5d-4xlarge
      , InstanceType.m5dn-large
      , InstanceType.m5dn-xlarge
      , InstanceType.m5dn-2xlarge
      , InstanceType.m5dn-4xlarge
      , InstanceType.m5n-large
      , InstanceType.m5n-xlarge
      , InstanceType.m5n-2xlarge
      , InstanceType.m5n-4xlarge
      , InstanceType.m6g-medium
      , InstanceType.m6g-large
      , InstanceType.m6g-xlarge
      , InstanceType.m6g-2xlarge
      , InstanceType.m6g-4xlarge
      , InstanceType.m6gd-medium
      , InstanceType.m6gd-large
      , InstanceType.m6gd-xlarge
      , InstanceType.m6gd-2xlarge
      , InstanceType.m6gd-4xlarge
      , InstanceType.r5-large
      , InstanceType.r5-xlarge
      , InstanceType.r5-2xlarge
      , InstanceType.r5-4xlarge
      , InstanceType.r5d-large
      , InstanceType.r5d-xlarge
      , InstanceType.r5d-2xlarge
      , InstanceType.r5d-4xlarge
      , InstanceType.r5a-large
      , InstanceType.r5a-xlarge
      , InstanceType.r5a-2xlarge
      , InstanceType.r5a-4xlarge
      , InstanceType.r5ad-large
      , InstanceType.r5ad-xlarge
      , InstanceType.r5ad-2xlarge
      , InstanceType.r5ad-4xlarge
      , InstanceType.r5n-large
      , InstanceType.r5n-xlarge
      , InstanceType.r5n-2xlarge
      , InstanceType.r5n-4xlarge
      , InstanceType.r5dn-large
      , InstanceType.r5dn-xlarge
      , InstanceType.r5dn-2xlarge
      , InstanceType.r5dn-4xlarge
      , InstanceType.r6g-medium
      , InstanceType.r6g-large
      , InstanceType.r6g-xlarge
      , InstanceType.r6g-2xlarge
      , InstanceType.r6g-4xlarge
      , InstanceType.r6gd-medium
      , InstanceType.r6gd-large
      , InstanceType.r6gd-xlarge
      , InstanceType.r6gd-2xlarge
      , InstanceType.r6gd-4xlarge
      , InstanceType.t3-nano
      , InstanceType.t3-micro
      , InstanceType.t3-small
      , InstanceType.t3-medium
      , InstanceType.t3-large
      , InstanceType.t3-xlarge
      , InstanceType.t3-2xlarge
      , InstanceType.t3a-nano
      , InstanceType.t3a-micro
      , InstanceType.t3a-small
      , InstanceType.t3a-medium
      , InstanceType.t3a-large
      , InstanceType.t3a-xlarge
      , InstanceType.t3a-2xlarge
      , InstanceType.t4g-nano
      , InstanceType.t4g-micro
      , InstanceType.t4g-small
      , InstanceType.t4g-medium
      , InstanceType.t4g-large
      , InstanceType.t4g-xlarge
      , InstanceType.t4g-2xlarge
      , InstanceType.x2gd-medium
      , InstanceType.x2gd-large
      , InstanceType.x2gd-xlarge
      , InstanceType.x2gd-2xlarge
      , InstanceType.x2gd-4xlarge
      ]
    }
